version: "3.1"

services:

  logstash:
    image: logstash:2
    volumes:
          - ./:/config
    command: logstash -f /config/logstash.conf
    links:
     - elasticsearch
    depends_on:
     - elasticsearch

  elasticsearch:
     image: elasticsearch:5.5.2
     ports:
      - "9200:9200"
     volumes:
      - "./es_data/es_data:/usr/share/elasticsearch/data/"


  kibana:
    image: kibana:5
    ports:
     - "5601:5601"
    links:
     - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
     - elasticsearch



